### ISSUE TITLE
build problem: eslint-import-resolver-webpack engine node

### ISSUE THREAD

**Issue by HeikoNardmann** [fossteams/fossteams-frontend#4]
By today I've tried to compile this project on my Ubuntu 20.04 system and received the following:
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error eslint-import-resolver-webpack@0.13.1: The engine "node" is incompatible with this module. Expected version "^16 || ^15 || ^14 || ^13 || ^12 || ^11 || ^10 || ^9 || ^8 || ^7 || ^6". Got "18.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command
```
Using
```
yarn install --ignore-engines
```
seems to be fine. Although - as I'm new to yarn - I have no idea what this leads to:
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@vue/eslint-config-airbnb > eslint-import-resolver-webpack@0.13.1" has unmet peer dependency "webpack@>=1.11.0".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 3.91s.
```

**Comment by HeikoNardmann** [comment]
Then `yarn build` gives me
```
yarn run v1.22.19
$ vue-cli-service build
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

⠹  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
⠋  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
⠸  Building for production.../home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/cache-loader/dist/index.js:147:7
    at /home/heikonardmann/projects/trunk/Git-Repos/fossteams-frontend/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
